version: "3.8"

services:
  # Banco de Dados MongoDB
  mongo:
    container_name: mongo_db_tech_5
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    env_file:
      - .env

  # API de Recomendação com FastAPI
  api:
    container_name: api_tech_5
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - mongo
    env_file:
      - .env

  # Serviço de Treinamento de Machine Learning
  training:
    container_name: training_tech_5
    build:
      context: .
      dockerfile: Dockerfile.training
    restart: "no"
    depends_on:
      - mongo
    volumes:
      - ./models:/app/models  # Armazenar modelos treinados
    env_file:
      - .env

volumes:
  mongo-data:
