version: '3.8'

services:
  mongo:
    container_name: mongo_db_tech_5
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    restart: always

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  mlflow:
    container_name: mlflow_server
    image: ghcr.io/mlflow/mlflow:v2.10.1
    ports:
      - "${MLFLOW_PORT:-8080}:8080"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:8080
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
    volumes:
      - mlflow_data:/mlflow
    command: mlflow server --host 0.0.0.0 --port 8080 --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /mlflow/artifacts
    restart: always

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: api_service
    depends_on:
      - mongo
      - mlflow
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - ../.env
    volumes:
      - ../app:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  train:
    build:
      context: ..
      dockerfile: docker/Dockerfile.train
    container_name: train_service
    depends_on:
      - mongo
      - mlflow
    env_file:
      - ../.env
    volumes:
      - ../train:/train
    command: ["python", "/train/train.py"]

volumes:
  mongo-data:
  mlflow_data: