# Usar imagem oficial do Python
FROM python:3.10

# Definir diretório de trabalho dentro do container
WORKDIR /app

# Copiar arquivos necessários
COPY ../requirements-api.txt /app/requirements.txt
COPY ../app /app

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta da API
EXPOSE 8000

# Definir comando para iniciar a API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
