version: '3.8'

services:
  mongo:
    container_name: mongo_db_tech_5
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: api_service
    depends_on:
      - mongo
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - ../.env
    volumes:
      - ../app:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  train:
    build:
      context: ..
      dockerfile: docker/Dockerfile.train
    container_name: train_service
    depends_on:
      - mongo
    env_file:
      - ../.env
    volumes:
      - ../train:/train
    command: ["python", "/train/train.py"]

volumes:
  mongo-data:
